### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mtzmedia** [harrytang/yii2-fineuploader#2]
Sorry if this is the wrong place to ask, but I'm having a hard time getting this going. I installed with composer, but I didn't do anything with the config files and this is what I have on my page:

<code><? use harrytang\fineuploader\Fineuploader; ?></code>
<code>< div class="uploader">< /div></code>
<code><?= Fineuploader::widget([ ]); ?></code>

I'm getting this error: "Invalid path alias: @harrytang/fineuploader/assets"

Any help with this error, and installation in general, would be greatly appreciated!!

**Comment by harrytang** [comment]
Hi, plz try v1.0.1, if any problem plz let me know. thanks

**Comment by mtzmedia** [comment]
Harry,

Thanks for getting back to me so quickly! I installed v1.0.1 and got the same error. I modified FineuploaderAsset.php line 15 to this:

<code>public $sourcePath = '@vendor/harrytang/yii2-fineuploader/assets';</code>

Which get's me past the initial error, but now I get "Error: Cannot find template script at ID 'qq-template'!" in jquery.fine-uploader.js.

Do you have any example code of usage? Maybe I'm just not calling the widget correctly?

**Comment by mtzmedia** [comment]
Hello Harry,

I'm trying to get this extension to run the Amazon S3 uploader. I figured out the path issue. Is this the correct way to get it to use the Amazon S3 assets?

```
'assetManager' => [
  'bundles' => [
    harrytang\fineuploader\FineuploaderAsset' => [
      'js' => [ 's3.jquery.fine-uploader/s3.jquery.fine-uploader.js' ],
      'css' => [ 's3.jquery.fine-uploader/fine-uploader.min.css' ]
    ],
  ],
],
```

But then what? It seems to be one error after another!

**Comment by mtzmedia** [comment]
For example, without overriding the assets, I get this error:

```
Error: Cannot find template script at ID 'qq-template'!
```

With the s3 assets, I get this error:

```
TypeError: handlerType is undefined
```

**Comment by mtzmedia** [comment]
Figured out the reason for these errors... Everything is hard-coded to only work with the traditional setup. Also, this is probably a different issue but it seems it cannot handle functions in the options.
